In [17]:
import numpy as np

# initialize a data array with 3 x 4 matrix
# 3 input nodes to the network and 4 training examples.
input_data = np.array([[0,0,1],
                      [0,1,1],
                      [1,0,1],
                      [1,1,1]])

# while output is label with 4 x 1 matrix            
output_labels = np.array([[0],
                          [1],
                          [1],
                          [0]])

# Print the input data and output
print(input_data)
print(output_labels)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]
[[0]
 [1]
 [1]
 [0]]


Construct the sigmoid function to provide probability as output

In [0]:
# sigmoid function
def activate(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    # Logistic Function
    return 1/(1+np.exp(-x))

In [19]:
# Random initialize values for weight of output
#it is a neural network with two layers of weights
# Since the input is 3 x 4 matrix, it initialized randomly
# which requires a matrix of dimensionality (3,4)
weight_0 = 2*np.random.random((3,4)) - 1

# Initialize randomly as output label is 4 x 1 matrix 
weight_1 = 2*np.random.random((4,1)) - 1

# check the values of weight
print(weight_0)
print(weight_1)

[[ 0.91577906  0.06633057  0.38375423 -0.36896874]
 [ 0.37300186  0.66925134 -0.96342345  0.50028863]
 [ 0.97772218  0.49633131 -0.43911202  0.57855866]]
[[-0.79354799]
 [-0.10421295]
 [ 0.81719101]
 [-0.4127717 ]]


In [21]:
for j in range(60000):

	# Forward propagate through layers 0, 1, and 2
    layer0 = input_data
    layer1 = activate(np.dot(layer0,weight_0))
    layer2 = activate(np.dot(layer1,weight_1))

    #calculate error for layer 2
    layer2_error = output_labels - layer2
    
    if (j% 10000) == 0:
        print ("Error:" + str(np.mean(np.abs(layer2_error))))
        
    #Use it to compute the gradient
    layer2_gradient = layer2_error*activate(layer2,deriv=True)

    #calculate error for layer 1
    layer1_error = layer2_gradient.dot(weight_1.T)
    
    #Use it to compute its gradient
    layer1_gradient = layer1_error * activate(layer1,deriv=True)
    
    #update the weights using the gradients
    weight_1 += layer1.T.dot(layer2_gradient)
    weight_0 += layer0.T.dot(layer1_gradient)

Error:0.4992605157018889
Error:0.010472325449007145
Error:0.00719099967914128
Error:0.005790451679254119
Error:0.00497056455036363
Error:0.0044174494977260205


Based on the output values above, the error at the last one is smaller than initially error. Below line is to check the layer1 and layer2 after dot product.

In [23]:
print(layer1)
print(layer2)

[[9.38630273e-01 4.99643586e-01 4.84236342e-02 7.32829372e-01]
 [4.36310798e-02 9.56597112e-01 3.97840344e-05 6.66908863e-01]
 [9.99942289e-01 9.40578243e-01 9.56505242e-01 4.15680797e-01]
 [9.81018532e-01 9.97145831e-01 1.69028234e-02 3.41792167e-01]]
[[0.00291805]
 [0.99570697]
 [0.99597618]
 [0.00481525]]
