**Without Neural Network**

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
c = tf.constant(5.0)
total = a + b + c
print(a)
print(b)
print(c)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()
print(sess.run(total))

12.0


In [4]:
print(sess.run({'abc':(a, b, c), 'total':total}))

{'abc': (3.0, 4.0, 5.0), 'total': 12.0}


In [0]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x * y

In [6]:
print(sess.run(z, feed_dict={x:5, y:2}))

10.0


**With Basic Neural Network**

In [0]:
x = tf.constant([[10],[20],[3],[4]],dtype=tf.float32)
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [0]:
# Calling tf.global_variables_initializer only creates and returns a handle to a TensorFlow operation.
#That op will initialize all the global variables when we run it with tf.Session.run.
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [0]:
y_true = tf.constant([[1],[2],[30],[40]])

In [10]:
y_pred = linear_model(x)
print(y_pred)

Tensor("dense/BiasAdd_1:0", shape=(4, 1), dtype=float32)


In [12]:
print(sess.run(y_pred))

[[-4.166664 ]
 [-8.333328 ]
 [-1.2499992]
 [-1.6666656]]


In [13]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y)

print(sess.run(loss))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
711.5364


In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [15]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

711.5364
923.63666
1504.0325
3072.513
7292.1504
18625.438
49046.496
130685.29
349755.53
937593.0
2514935.8
6747401.0
18104304.0
48578090.0
130347840.0
349759170.0
938501600.0
2518263300.0
6757207600.0
18131495000.0
48651887000.0
130546670000.0
350293430000.0
939935900000.0
2522112300000.0
6767539400000.0
18159216000000.0
48726295000000.0
130746400000000.0
350829300000000.0
941373800000000.0
2525971000000000.0
6777891000000000.0
1.8186994e+16
4.8800814e+16
1.3094634e+17
3.5136588e+17
9.428136e+17
2.5298341e+18
6.7882583e+18
1.8214806e+19
4.8875464e+19
1.3114665e+20
3.5190336e+20
9.442556e+20
2.5337038e+21
6.7986385e+21
1.8242663e+22
4.89502e+22
1.313472e+23
3.5244155e+23
9.457e+23
2.53758e+24
6.8090414e+24
1.8270574e+25
4.9025105e+25
1.3154817e+26
3.5298085e+26
9.471468e+26
2.5414614e+27
6.819455e+27
1.8298521e+28
4.9100097e+28
1.3174934e+29
3.535206e+29
9.485955e+29
2.5453492e+30
6.829889e+30
1.8326516e+31
4.9175214e+31
1.31950965e+32
3.540616e+32
9.50047e+32
2.549244e+33
6.84034e+33
1

In [16]:
print(sess.run(y_pred))

[[-2.7042609e+22]
 [-5.3895468e+22]
 [-8.2456073e+21]
 [-1.0930893e+22]]


The model is to totally cant predict the value as the actual function is not linear. Below example is a linear model prediction.

In [0]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
# the expected output for each input, y_true
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [0]:
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x)

In [25]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[1.2462496]
 [2.492499 ]
 [3.7387486]
 [4.984998 ]]


In [26]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)
print(sess.run(loss))

27.61103


In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [32]:
for i in range(1000):
  _, loss_value = sess.run((train, loss))

print(loss_value)

2.8595636e-05


In [33]:
print(sess.run(y_pred))

[[-0.0086087]
 [-1.0041716]
 [-1.9997344]
 [-2.9952972]]
